#! This is the main docker-compose file, that others files extends the common docker structure from it
version: "3"

# containers that i wanna use
services:
  express-docker-app:
    container_name: express-docker-container
    # build: . # we should write the path of DockerFile, Also i can only write . and docker compose is smart enough to search and find File
    ports:
      - "4000:4000" # hostPort:containerPort
    env_file: # here i can use .env file and reach all vars inside it
      - ./.env
    depends_on:
      # - mongo
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#! Because we switched to postgreSql
#   mongo:
#     image: mongo
#     restart: always
#     volumes:
#       - mongo-db:/data/db # volumeName:containerPath
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINPASSWORD: password
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
#       ME_CONFIG_BASICAUTH: false

volumes:
  mongo-db:
  postgres-db:
